version: '3'

services:
  db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_DB=certeverus
        - POSTGRES_USER=db
        - POSTGRES_PASSWORD=certeverus
      ports:
          - "5432:5432"

  nginx:
      image: nginx
      container_name: nginx
      volumes:
          - ./frontend/dist/:/usr/share/nginx/html:ro
      ports:
          - "8080:80"
      environment:
          - NGINX_PORT=80

  app:
      build: .
      container_name: app
      restart: always
      command: >
        sh -c '
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py loaddata fixtures/initial.json
          export DOCKER=1
          python manage.py runserver 0.0.0.0:8000'
      volumes:
          - .:/app
      ports:
          - "8000:8000"
      environment: 
          - DOCKER=1
      # depends_on:
      #     - db
      #     - nginx
